### ISSUE TITLE
Corruption caused by concurrent reverse deletes

### ISSUE THREAD

**Issue by broneill** [cojen/Tupl#47]
- Thread0 is inserting entries in random order into index0
- Thread1 is iterating over index0 and moving entries to index1
- Thread2 is iterating over index1 in reverse and moving entries to index2

Sometimes this happens:

PANIC: Closing database due to unhandled exception: java.lang.AssertionError: Already in NodeMap: LeafNode: {id=290175, cachedState=3, isSplit=false, availableBytes=1364, extremity=0b0, latchState=org.cojen.tupl.Node@7cca494b[State = -2147483648, empty queue]}, LeafNode: {id=290175, cachedState=0, isSplit=false, availableBytes=4, extremity=0b0, latchState=org.cojen.tupl.Node@7ba4f24f[State = 0, empty queue]}, 290175
        at org.cojen.tupl.LocalDatabase.nodeMapPut(LocalDatabase.java:2706)
        at org.cojen.tupl.LocalDatabase.nodeMapPut(LocalDatabase.java:2685)
        at org.cojen.tupl.LocalDatabase.doMarkDirty(LocalDatabase.java:3170)
        at org.cojen.tupl.LocalDatabase.markDirty(LocalDatabase.java:3045)
        at org.cojen.tupl.TreeCursor.notSplitDirty(TreeCursor.java:3626)
        at org.cojen.tupl.TreeCursor.store(TreeCursor.java:2382)
        at org.cojen.tupl.TreeCursor.doFindAndStore(TreeCursor.java:2116)
        at org.cojen.tupl.TreeCursor.findAndStore(TreeCursor.java:2084)
        at org.cojen.tupl.Tree.store(Tree.java:355)

When verifying the database:

Verification failure: index=1593915264256456714, node=290175, level=4: Child keys are not less than parent key: BottomInternalNode: {id=547076, cachedState=0, isSplit=false, availableBytes=7, extremity=0b0, latchState=org.cojen.tupl.Node@25f38edc[State = 0, empty queue]}

In most cases, the node in the assertion is not the one found by verification. The following causes have been ruled out:

- Version 1.3 is not to blame. Problem was reproduced with version 1.2.
- Node recycling is not to blame. Disabling it didn't prevent the problem.

It appears that a leaf node was deleted, but for some reason it was still referenced by the parent node. The reference also still exists in the node map, which is at least consistent.

**Comment by broneill** [comment]
The particular stress test is relatively old, and it was last run on version 1.1.0. It's possible that the bug existed then as well, considering that the node map feature wasn't used then. Without it, detecting the problem would require full verification.

**Comment by broneill** [comment]
Examination of the free list shows that some pages are duplicated. org.cojen.tupl.CorruptDatabaseException: Doubly freed page: 719249

**Comment by broneill** [comment]
When a node is marked as dirty, the old page is getting double deleted. No evidence shows double allocation, however.

**Comment by broneill** [comment]
Problem appears to go away when tryRebalanceInternalRight is disabled.

**Comment by broneill** [comment]
This change fixes several a few bad practices and fixes an assertion failure, but the original problem remains. SHA-1 a99c4a989a178e00b913388c8c4ada40d8823ef1

**Comment by broneill** [comment]
Fixed in change a99c4a989a178e00b913388c8c4ada40d8823ef1 and f7e8e8da1a59c9ce83910a09aa203d30b3b74fbc. The primary problem was in the code that handles the "parent event before child" case. A node cannot be evicted when a cursor is bound to it. A thread which is making changes will dirty the nodes, and then assume that they stay dirty. If the node state switches to clean, then the changes get lost when the "clean" node is evicted.

**Comment by broneill** [comment]
Not fixed. It now takes longer to reproduce.

**Comment by broneill** [comment]
Problem doesn't appear to be caused by eviction order. Disabling internal node eviction doesn't prevent the problem.

**Comment by broneill** [comment]
This change is a big cause of the problem: fba5d86a06f72a55a609549d1a30123821bfc859

**Comment by broneill** [comment]
The `tryRebalanceInternalRight` method is still a culprit. The affected cursor frames appear to be bound wrong, but I cannot pinpoint the exact place where this happens.

**Comment by broneill** [comment]
I've not been able to find anything wrong with the rebalancing code itself, and when disabled, I did see the same double page delete problem. It just takes longer to reproduce, in this case, about 4 hours.

**Comment by broneill** [comment]
Running the test again with left and right internal node rebalancing disabled. One thing I noticed is that the rebalancing moves a key from the parent internal node down into a child internal node. This might interfere with suffix compression, and so an illegal key might move into the child node.

**Comment by broneill** [comment]
With all rebalancing disabled, the test fails after a few hours like so:

"Attempt to read past end of file: 576460752109830144" and "Attempt to read past end of file: 576460751899832320"

The hex versions of these positions are 0x7FF_FFFF_F476_0000 and 0x7FF_FFFF_E7F1_B000. When divided by 4096, they're 0x7FFF_FFFF_4760 and 0x7FFF_FFFE_7F1B, which are 6-byte pointers.

Running a test now to see if the bogus positions are due to encoding, decoding, or something else.

**Comment by broneill** [comment]
Here's an interesting Java bug, relating to inlining and escape analysis:

https://bugs.openjdk.java.net/browse/JDK-8134031
http://stackoverflow.com/questions/32994608/java-8-odd-timing-memory-issue

I don't know if this is part of the problem, but many parts of the code are designed to be friendly to inlining and escape analysis. I'll switch to using a newer JVM which has the fix.

**Comment by broneill** [comment]
Root cause and fix: change #2f5d043558d87c254f9d120b3f7871d7ea74aa6e
