### ISSUE TITLE
Assertion error when running compaction stress test

### ISSUE THREAD

**Issue by broneill** [cojen/Tupl#62]
Failure in first assertion:

        // ...now they can be swapped...
        if (!CursorFrame.cLastUpdater.compareAndSet(this, thisLastFrame, childLastFrame)) {
            throw new AssertionError();
        }
        if (!CursorFrame.cLastUpdater.compareAndSet(child, childLastFrame, thisLastFrame)) {
            throw new AssertionError();
        }

Running org.cojen.tupl.CompactDirectTest
Exception in thread "Thread-154" java.lang.AssertionError
        at org.cojen.tupl._Node.doRootDelete(_Node.java:3958)
        at org.cojen.tupl._Node.rootDelete(_Node.java:3915)
        at org.cojen.tupl._TreeCursor.mergeInternal(_TreeCursor.java:4174)
        at org.cojen.tupl._TreeCursor.mergeLeaf(_TreeCursor.java:4150)
        at org.cojen.tupl._TreeCursor.store(_TreeCursor.java:2927)
        at org.cojen.tupl._TreeCursor.doFindAndModify(_TreeCursor.java:2791)
        at org.cojen.tupl._TreeCursor.findAndModify(_TreeCursor.java:2721)
        at org.cojen.tupl._Tree.replace(_Tree.java:379)
        at org.cojen.tupl.View.delete(View.java:222)
        at org.cojen.tupl.CompactTest.doStress(CompactTest.java:410)
        at org.cojen.tupl.CompactTest.stress(CompactTest.java:345)

**Comment by broneill** [comment]
Only two threads are active: The one which is deleting items from the tree and the one performing compaction.

**Comment by broneill** [comment]
I'm unable to reproduce the problem, but there is a problem in the Node.lockLastFrame method:

    /**
     * Lock the last frame, for use by the rootDelete method.
     */
    private CursorFrame lockLastFrame(CursorFrame lock) {
        for (CursorFrame f = mLastCursorFrame; f != null; f = f.mPrevCousin) {
            if (f.tryLock(lock) != null) {
                return f;
            }
        }
        throw new AssertionError();
    }

Corrected version:

    private CursorFrame lockLastFrame(CursorFrame lock) {
        while (true) {
            CursorFrame f = mLastCursorFrame;
            if (f.tryLock(lock) == f) {
                return f;
            }
            // Must keep trying against the last cursor frame instead of iterating to the
            // previous frame. The lock attempt failed because of a concurrent unbind, but the
            // last cursor frame reference might not have been updated yet. Assertions in the
            // doRootDelete method further verify that the locked frame is in fact the last,
            // with a compareAndSet call.
        }
    }
